<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pista;

class PistasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pistas = [
            [
                'nombre' => 'Polideportivo Carranque',
                'direccion' => 'Av. de Velázquez, 362, Málaga',
                'latitud' => 36.708561,
                'longitud' => -4.464039,
                'localidad' => 'Málaga',
                'precio_por_hora' => 50.00,
                'tipo_superficie' => 'cesped_artificial',
                'capacidad' => 14,
                'vestuario' => true,
                'parking' => true,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '09:00',
                'horario_cierre' => '23:00',
                'telefono' => '952 10 86 00',
                'descripcion' => 'Pista de fútbol 7 con césped artificial de última generación',
            ],
            [
                'nombre' => 'Ciudad Deportiva Carranque',
                'direccion' => 'Calle Ayala, 25, Málaga',
                'latitud' => 36.715123,
                'longitud' => -4.470234,
                'localidad' => 'Málaga',
                'precio_por_hora' => 45.00,
                'tipo_superficie' => 'cesped_artificial',
                'capacidad' => 10,
                'vestuario' => true,
                'parking' => true,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '08:00',
                'horario_cierre' => '22:00',
                'descripcion' => 'Pista de fútbol 5 ideal para partidos rápidos',
            ],
            [
                'nombre' => 'Complejo Deportivo La Mosca',
                'direccion' => 'Calle Mozart, s/n, Málaga',
                'latitud' => 36.720456,
                'longitud' => -4.415789,
                'localidad' => 'Málaga',
                'precio_por_hora' => 40.00,
                'tipo_superficie' => 'cesped_natural',
                'capacidad' => 22,
                'vestuario' => true,
                'parking' => false,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '10:00',
                'horario_cierre' => '21:00',
                'descripcion' => 'Pista de fútbol 11 con césped natural',
            ],
            [
                'nombre' => 'Polideportivo Ciudad Jardín',
                'direccion' => 'Av. de las Américas, 23, Málaga',
                'latitud' => 36.732189,
                'longitud' => -4.429876,
                'localidad' => 'Málaga',
                'precio_por_hora' => 55.00,
                'tipo_superficie' => 'cesped_artificial',
                'capacidad' => 14,
                'vestuario' => true,
                'parking' => true,
                'iluminacion' => true,
                'techada' => true,
                'horario_apertura' => '09:00',
                'horario_cierre' => '23:00',
                'telefono' => '952 23 45 67',
                'descripcion' => 'Pista cubierta de fútbol 7, ideal para lluvia',
            ],
            [
                'nombre' => 'Complejo El Palo',
                'direccion' => 'Paseo Marítimo El Pedregal, Málaga',
                'latitud' => 36.721369,
                'longitud' => -4.364823,
                'localidad' => 'Málaga',
                'precio_por_hora' => 60.00,
                'tipo_superficie' => 'cesped_artificial',
                'capacidad' => 14,
                'vestuario' => true,
                'parking' => true,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '08:00',
                'horario_cierre' => '23:00',
                'telefono' => '952 29 88 00',
                'descripcion' => 'Pista junto al mar con vistas espectaculares',
            ],
            [
                'nombre' => 'Polideportivo Intelhorce',
                'direccion' => 'Calle Fray Alonso de Santo Tomás, Málaga',
                'latitud' => 36.722567,
                'longitud' => -4.378901,
                'localidad' => 'Málaga',
                'precio_por_hora' => 35.00,
                'tipo_superficie' => 'cemento',
                'capacidad' => 10,
                'vestuario' => false,
                'parking' => false,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '10:00',
                'horario_cierre' => '20:00',
                'descripcion' => 'Pista básica de fútbol 5, económica',
            ],
            [
                'nombre' => 'Ciudad Deportiva La Rosaleda',
                'direccion' => 'Paseo de Martiricos, s/n, Málaga',
                'latitud' => 36.729845,
                'longitud' => -4.423456,
                'localidad' => 'Málaga',
                'precio_por_hora' => 70.00,
                'tipo_superficie' => 'cesped_natural',
                'capacidad' => 22,
                'vestuario' => true,
                'parking' => true,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '08:00',
                'horario_cierre' => '22:00',
                'telefono' => '952 61 05 00',
                'descripcion' => 'Campo profesional de fútbol 11',
            ],
            [
                'nombre' => 'Polideportivo Málaga Norte',
                'direccion' => 'Calle Periodista Federico Alba, Málaga',
                'latitud' => 36.742123,
                'longitud' => -4.428765,
                'localidad' => 'Málaga',
                'precio_por_hora' => 48.00,
                'tipo_superficie' => 'cesped_artificial',
                'capacidad' => 14,
                'vestuario' => true,
                'parking' => true,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '09:00',
                'horario_cierre' => '23:00',
                'descripcion' => 'Pista moderna de fútbol 7 en zona norte',
            ],
            [
                'nombre' => 'Complejo Deportivo Martiricos',
                'direccion' => 'Calle Pacífico, 54, Málaga',
                'latitud' => 36.726789,
                'longitud' => -4.419234,
                'localidad' => 'Málaga',
                'precio_por_hora' => 42.00,
                'tipo_superficie' => 'tierra',
                'capacidad' => 14,
                'vestuario' => true,
                'parking' => false,
                'iluminacion' => false,
                'techada' => false,
                'horario_apertura' => '10:00',
                'horario_cierre' => '19:00',
                'descripcion' => 'Pista de tierra para fútbol 7',
            ],
            [
                'nombre' => 'Polideportivo Tetúan',
                'direccion' => 'Calle Godino, 7, Málaga',
                'latitud' => 36.718234,
                'longitud' => -4.434567,
                'localidad' => 'Málaga',
                'precio_por_hora' => 38.00,
                'tipo_superficie' => 'cesped_artificial',
                'capacidad' => 10,
                'vestuario' => true,
                'parking' => false,
                'iluminacion' => true,
                'techada' => false,
                'horario_apertura' => '09:00',
                'horario_cierre' => '21:00',
                'descripcion' => 'Pista céntrica de fútbol 5',
            ]
        ];

        foreach($pistas as $pista){
            Pista::create($pista);
        }
    }
}
